CRM.WebManage/Controllers/ActionInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CRM.BLL;
using CRM.IBLL;
using CRM.Model;

namespace CRM.WebManage.Controllers
{
    public class ActionInfoController : BaseController
    {
        //首先实例化一个ActionInfo对象
        readonly IActionInfoService _actioninfoService = new ActionInfoService();
        readonly IRoleService _roleService = new RoleService();
        readonly IActionGroupService _actionGroupService = new ActionGroupService();

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取权限的所有的信息
        /// </summary>
        /// <returns></returns>
        public ActionResult GetActionUserInfoShow()
        {
            //首先获取前台传递过来的参数
            int pageIndex = Request["page"] == null ? 1 : Convert.ToInt32(Request["page"]);
            int pageSize = Request["rows"] == null ? 10 : Convert.ToInt32(Request["rows"]);

            //获取前台传递过来的数据实现进行模糊查询
            string searchActionName = Request["SearchActionName"];
            string searchRequestHttpType = Request["SearchRequestHttpType"];

            //定义对象，得到所有的参数值
            GetModelQuery actionInfo = new GetModelQuery
            {
                ActionName = searchActionName,
                pageIndex = pageIndex,
                pageSize = pageSize,
                RequestHttpType = searchRequestHttpType,
                total = 0
            };

            //调用方法，实现绑定所有的数据
            var data = from c in _actioninfoService.LoadDataActionInfo(actionInfo)
                       select new { c.ID, c.ActionName, c.ActionType, c.RequestUrl, c.RequestHttpType, c.SubTime };
            //var data = _actioninfoService.List(pageSize, pageIndex, out total, c => true, true, e => e.id);
            //获取前台需要的数据
            var jsonResult = new { total = actionInfo.total, rows = data };
            return Json(jsonResult, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 添加用户权限信息
        /// </summary>
        /// <param name="actioninfo"></param>
        /// <returns></returns>
        public ActionResult AddActionInfo(ActionInfo actioninfo)
        {
            actioninfo.SubTime = DateTime.Now;
            var result = _actioninfoService.Add(actioninfo);
            if (result.Code == ResultEnum.Success && result.Data.ID > 0)
            {
                return Content("OK");
            }
            return Content(result.Msg);
        }

        /// <summary>
        /// 绑定用户权限问题
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult BindActionInfo(int ID)
        {
            var jsonData = _actioninfoService.Get(c => c.ID == ID).FirstOrDefault();
            return Json(jsonData, JsonRequestBehavior.AllowGet);

        }

        /// <summary>
        /// 对用户权限信息进行修改
        /// </summary>
        /// <param name="actionInfo"></param>
        /// <returns></returns>
        public ActionResult UpdateActionInfo(ActionInfo actionInfo)
        {
            //首先查询出所有的用户权限信息
            ActionInfo editActionInfo = _actioninfoService.Get(c => c.ID == actionInfo.ID).FirstOrDefault();
            if (editActionInfo == null)
            {
                return Content("修改错误，请您检查");
            }
            //给要修改的实体对象赋值
            editActionInfo.ActionName = actionInfo.ActionName;
            editActionInfo.RequestHttpType = actionInfo.RequestHttpType;
            editActionInfo.RequestUrl = actionInfo.RequestUrl;
            editActionInfo.ActionType = actionInfo.ActionType;
            //进行修改信息
            var result = _actioninfoService.Update(editActionInfo);
            if (result.Code == ResultEnum.Success && result.Data > 0)
            {
                return Content("OK");
            }
            return Content(result.Msg);
        }

        /// <summary>
        /// 多选删除用户信息
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult DeleteActionInfo(string ID)
        {
            if (string.IsNullOrEmpty(ID))
            {
                return Content("请选择您要删除的数据");
            }
            var deleteId = ID.Split(',');

            //定义List集合存放这些需要删除的数据
            List<int> list = deleteId.Select(id => Convert.ToInt32(id)).ToList();

            //实现删除多条数据的方法
            var result = _actioninfoService.DeleteActionInfo(list);
            if (result.Code == ResultEnum.Success && result.Data > 0)
            {
                return Content("OK");
            }
            return Content(result.Msg);
        }

        /// <summary>
        /// 实现设置权限角色信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SetRole(int id)
        {
            //首先根据传递过来的ID找到权限信息
            var currrentSetRoleAction = _actioninfoService.Get(u => u.ID == id).FirstOrDefault();
            ViewData.Model = currrentSetRoleAction;

            //传递过去前台需要用到的数据,遍历角色，显示出来
            short RoleNomal = (short)DelFlagEnum.None;
            var allRoles = _roleService.Get(c => c.DelFlag == RoleNomal).ToList();
            ViewBag.AllRoles = allRoles;

            //传递给前台权限对应的角色信息，方便用户给角色设置权限
            ViewBag.ExistRoleIds = (from n in currrentSetRoleAction.Role  //权限和角色表的中间表的数据
                                    select n.ID).ToList();

            return View();
        }

        /// <summary>
        /// 处理权限的的请求，添加角色信息，
        /// </summary>
        /// <returns></returns>
        [HttpPost ]
        public ActionResult SetRole()
        {
            //首先读取到前台传递过来的权限ID
            int actionId = Request["hidenActionID"] == null ? 0 : Convert.ToInt32(Request["hidenActionID"]);
            //查询出当前权限的所有的信息,根据Action
            var currentActionInfo = _actioninfoService.Get(c => c.ID == actionId).FirstOrDefault();
            if (currentActionInfo != null)
            {
                //判断如果权限信息不为空的话执行，拿到前台表单传递的信息，进行操作，ckb_1,ckb_2,ckb_3
                var allKeys = from key in Request.Form.AllKeys
                              where key.Contains("ckb_")
                              select key;
                //定义一个List集合存放传递过来的Key
                List<int> list = new List<int>();
                if (actionId > 0)
                {
                    //循环便利所有的前台的信息展示给用户显示
                    foreach (var key in allKeys)
                    {
                        list.Add(Convert.ToInt32(key.Replace("ckb_", "")));
                    }
                }
                var result = _actioninfoService.SetRole(actionId, list);
                if (result.Code == ResultEnum.Success && result.Data)
                {
                    return Content("OK");
                }
                return Content(result.Msg);
            }
            return Content("无效的数据");
        }

        /// <summary>
        /// 获取设置用户分组的信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SetAction(int id)
        {
            //根据ID查询出权限信息的信息
            var currentUser = _actioninfoService.Get(u => u.ID == id).FirstOrDefault();
            ViewData.Model = currentUser;

            //根据传递过去的菜单组获取到所有的菜单组信息
            short ActionID = (short)DelFlagEnum.None;
            var allAction = _actionGroupService.Get(c => c.DelFlag == ActionID).ToList();
            ViewBag.AllAction = allAction; 
            //然后传递给前台判断权限组数据是否被选中
            ViewBag.Exists = (from n in currentUser.ActionGroup  //获取到权限表
                           select n.ID).ToList();
            return View();
        }

        /// <summary>
        /// 对权限里面的权限分组设置菜单组的操作
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SetAction()
        {
            //首先根据前台传递过来的隐藏域得到actionID
            int actionId = Request["hidenActionID"] == null ? 0 : Convert.ToInt32(Request["hidenActionID"]);
            //根据actionID查询出来当前权限对应的ID
            var currentActionInfo = _actioninfoService.Get(c => c.ID == actionId).FirstOrDefault();
            if (currentActionInfo != null)
            {
                //拿到前台表单传递的表单选中值，形势为act_1，act_2,act_3
                var allKeys = from key in Request.Form.AllKeys
                              where key.Contains("act_")
                              select key;
                //定义一个集合用来存放传递过来的Key
                List<int> list = new List<int>();
                //循环遍历得到所有的前台数据显示在这里
                if (actionId > 0)
                {
                    foreach (var key in allKeys)
                    {
                        list.Add(Convert.ToInt32(key.Replace("act_", "")));
                    }
                }
                var result = _actioninfoService.SetAction(actionId, list);
                if (result.Code == ResultEnum.Success && result.Data)
                {
                    return Content("OK");
                }
                return Content(result.Msg);
            }
            return Content("无效的数据");
        }
    }
}

CRM.WebManage/Views/ActionInfo/SetAction.cshtml
@model CRM.Model.ActionInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>SetAction</title>
    <script src="../../Scripts/jquery-1.7.1.js"></script>
    <script src="../../Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function AfterSetAction(data) {
            if (data == "OK") {
                //调用父容器的方法，传递参数关闭层
                window.parent.AfterSetAction();
            }
            else {
                alert("权限角色设置出错，请您检查");
            }
        }
    </script>
</head>
<body>
    <h3>欢迎您给权限:<font color="red" size="5">@Model.ActionName </font>设置分组信息:</h3>
    <hr />
    
    <fieldset>
        <legend>设置权限分组信息</legend>
      @using(Ajax.BeginForm("SetAction","ActionInfo",new AjaxOptions(){OnSuccess="AfterSetAction"},new{id="frmSetRole"})){
            //存放一个隐藏域，用来给前台传递权限的ID
            <input type="hidden" name="hidenActionID" value="@Model.ID" />
            //ViewBag.AllAction ，ViewBag.Exists         
          List<CRM.Model.ActionGroup> allActions = (List<CRM.Model.ActionGroup>)ViewBag.AllAction;
          List<int> Exists = (List<int>)ViewBag.Exists;
          for (int i = 0; i < allActions.Count; i++)
          {
              if (i % 4 == 0)
              {
                  <br />
              }
              string str = "act_" + allActions[i].ID;
              //判断当前的菜单组有没有被选中到权限里面
              if (Exists.Contains(allActions[i].ID))
              {
                  <input type="checkbox" checked="checked" name="@str" value=" @str" id="@str" />
              }
              else
              {
                  <input type="checkbox" name="@str" value=" @str" id="@str" />
              }
              <label for="@str">@allActions[i].GroupName</label><span>&nbsp;&nbsp;</span>
          }
        <br />
        <div style="text-align:center;">
            <input type="submit" value="设置权限角色" />
        </div>
      }
    </fieldset>
</body>
</html>

CRM.WebManage/Views/ActionInfo/SetRole.cshtml
@model CRM.Model.ActionInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>SetRole</title>
    <script src="../../Scripts/jquery-1.7.1.js"></script>
    <script src="../../Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        function AfterSetRole(data) {
            if (data == "OK") {
                //调用父容器的方法，传递参数关闭层
                window.parent.AfterSetRole();
            }
            else {
                alert("权限角色设置出错，请您检查");
            }
        }
    </script>
</head>
<body>
    
    <h3>欢迎您给权限:<font color="red" size="5">@Model.ActionName </font>设置角色信息:</h3>
    <hr />
    
    <fieldset>
        <legend>请选择您需要设置给权限设置的角色</legend>
        @using(Ajax.BeginForm("SetRole","ActionInfo",new AjaxOptions(){OnSuccess="AfterSetRole"},new{id="frmSetRole"})){
            //存放一个隐藏域，用来给前台传递权限的ID
            <input type="hidden" name="hidenActionID" value="@Model.ID" />
                      
            List<CRM.Model.Role> allRoles = (List<CRM.Model.Role>)ViewBag.AllRoles;
            List<int> ExistRoleIds=(List<int>)ViewBag.ExistRoleIds;
            for (int i = 0; i < allRoles.Count; i++)
            {
                if(i%3==0)
                {
                    <br />
                }
                string str = "ckb_" + allRoles[i].ID;
                //判断当前的角色有没有加入到权限里面取，如果在里面，直接显示选中即可，否则不显示 
                if(ExistRoleIds.Contains(allRoles[i].ID))
                {         
                    <input type="checkbox" checked="checked" name="@str" value=" @str" id="@str" />
                }
                else
                {
                    <input type="checkbox" name="@str" value=" @str" id="@str" />  
                }
                <label for="@str">@allRoles[i].RoleName</label><span>&nbsp;&nbsp;</span>
            }
            <br />
            <div style="text-align:center;">
                <input type="submit" value="设置权限角色" />
            </div>
        }
    </fieldset>
</body>
</html>